# Site wide configuration

title: Kite-Mallorca.com - VDWS International Kiteboarding Center
description: Mallorcas kitesurfing school number one
logo: kite-mallorca_150x118.png
teaser: # 400x250 px default teaser image used in image archive grid
locale:
url: https://kite-mallorca.com

# Jekyll configuration

sass:
    sass_dir: _sass
    style: compressed
permalink: /:categories/:title/
markdown: kramdown
plugins:
  - jekyll-sitemap
  - jekyll-redirect-from
  - jekyll-zopfli
  - jekyll-brotli
compress_html:
  clippings: [script]
# Site owner
owner:
  name: Kitesurf Mallorca SL
  email: team@kite-mallorca.com
  twitter: kite_mallorca
  google: Kitesurf Mallorca
  fb_app_id:
  bio:
  avatar: bio-photo.jpg # 160x160 px image for author byline
disqus-shortname:


exclude: ["lib", "config.rb", ".sass-cache", "Capfile", "config", "log", "Rakefile", "Rakefile.rb", "tmp", "*.sublime-project", "*.sublime-workspace", "Gemfile", "Gemfile.lock", "README.md", "LICENSE", "node_modules", "Gruntfile.js", "package.json"]
